### ISSUE TITLE
KeyError: 'wanted_by'  

### ISSUE THREAD

**Issue by Madoshakalaka** [kootenpv/sysdm#3]
sysdm version 0.8.43 on python 3.6

```
$ sysdm create test.py
Creating systemd unit...
Traceback (most recent call last):
  File "/home/matt/.local/share/virtualenvs/dsystem-B3vl4kby/bin/sysdm", line 8, in <module>
    sys.exit(main())
  File "/home/matt/.local/share/virtualenvs/dsystem-B3vl4kby/lib/python3.6/site-packages/sysdm/__main__.py", line 261, in main
    _main()
  File "/home/matt/.local/share/virtualenvs/dsystem-B3vl4kby/lib/python3.6/site-packages/sysdm/__main__.py", line 179, in _main
    service_name = install(args)
  File "/home/matt/.local/share/virtualenvs/dsystem-B3vl4kby/lib/python3.6/site-packages/sysdm/sysctl.py", line 286, in install
    service_name, service = create_service_template(args)
  File "/home/matt/.local/share/virtualenvs/dsystem-B3vl4kby/lib/python3.6/site-packages/sysdm/sysctl.py", line 113, in create_service_template
    install = "[Install]\nWantedBy={wanted_by}".format(wanted_by)
KeyError: 'wanted_by'
```

**Comment by kootenpv** [comment]
Thanks a lot for reporting! Fixed per 0.8.44
